services:
  slinger:
    image: ghcr.io/crhiles/slinger2:main
    volumes:
      - /docker/volumes/slinger/config:/config:rw
    ports:
      - "65432:65432"
    user: 1001:1001
    network_mode: host
    environment:
      - TZ=America/Regina
